name: Gitleaks Scan

on:
  push:
    branches: [ "main", "feature/*", "demo/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Gitleaks
        run: |
          GITLEAKS_VERSION=8.28.0
          wget -q https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz
          tar -xvzf gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz gitleaks
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks with custom config
        run: |
          gitleaks detect \
            --source . \
            --redact \
            --config gitleaksconfig.toml \
            --exit-code 1
